#!/bin/bash
# tmux status bar configuration

ssh_sign() {
  echo -n '#[fg=yellow,bg=black,bold]' $(hostname)'#[fg=white] '
}
load_average() {
  echo -n '#[fg=white,bg=magenta,bold] '
  echo -n '('$(uptime | grep -oE \[0-9\]+\[.\]\[0-9\]+\[0-9\]+)') '
}
ip_address() {
  echo -n '#[fg=white,bg=blue,bold] '
  if type ip >/dev/null ; then
     echo -n $(ip addr |
       grep inet |
       grep -v 127.0.0.1 |
       grep -v \:\:1 |
       grep brd |
       grep -oE \(\[0-9\]\{1,3\}\[.\]\[0-9\]\{1,3\}\[.\]\[0-9\]\{1,3\}\[.\]\[0-9\]\{1,3\}\)/ |
       grep -oE \(\[0-9\]\{1,3\}\[.\]\[0-9\]\{1,3\}\[.\]\[0-9\]\{1,3\}\[.\]\[0-9\]\{1,3\}\))' '
  elif type ifconfig >/dev/null ; then
    echo -n $(ifconfig |
      grep -oE "inet [0-9.]{7,15}" |
      grep -v 127.0.0.1 |
      grep -v \:\:1 |
      sed "s/inet //g")' '
  fi
}
external_ip() {
  if type extip >/dev/null ; then
    echo -n '#[fg=white,bg=blue] '
    extip | grep -oE \(\[0-9\]\{1,3\}\[.\]\[0-9\]\{1,3\}\[.\]\[0-9\]\{1,3\}\[.\]\[0-9\]\{1,3\}\)
    echo -n ' '
  fi
}
cpu_temp() {
  if type sensors >/dev/null ; then
    echo -n '#[fg=white,bg=red,bold] '
    echo -n $(sensors | grep 'Core 0' | grep -oE \[0-9\.\]*\.C | head -n 1)' '
  fi
}
acpi_battery() {
  if type acpi >/dev/null && acpi | grep Battery >/dev/null ; then
    if [ "$(acpi -b | grep -oE Discharging)" = "Discharging" ] ; then
      echo -n '#[fg=black,bg=yellow,bold] '
      echo -n $(acpi -b | grep 'Battery' | grep -oE \[0-9\]\[0-9\]:\[0-9\]\*)
      echo -n ' '
    else
      echo -n '#[bg=green,fg=white,bold] '
    fi
    echo -n '('
    echo -n $(acpi -b | grep -oE \[0-9\]+%)
    echo -n ')'
    echo -n ' '
  fi
}


if [ "$1" = left ] ; then
  # left status bar expansion for SSH
  if [ "$SSH_CONNECTION" != "" ] ; then
    ssh_sign
  fi
elif [ "$1" = right ] ; then
  # right status bar
  # display both (non-SSH and SSH session)
  load_average
  if [ "${SSH_CONNECTION:+mayuge}" != "mayuge" ] ; then
    # for non-SSH client
    cpu_temp
    acpi_battery
  fi
fi

# reset format
echo '#[default]'

