#!/bin/sh

if hash open &>/dev/null ; then
  cmd="open"
elif hash exo-open &>/dev/null ; then
  cmd="exo-open"
elif hash xdg-open &>/dev/null ; then
  cmd="xdg-open"
elif hash gnome-open &>/dev/null ; then
  cmd="gnome-open"
else
  echo "Error: there are no command to open file or directory"
  exit 1
fi

if [ $# -gt 0 ] ; then
  echo "exec: $cmd $@"
  $cmd "$@"
else
  echo "exec: $cmd ."
  $cmd .
fi
