#!/bin/bash

NO_WAIFU2X=0
NO_OPTIPNG=0

_usage() {
  echo 'Usage: $0 [-nw|--no-waifu2x] [-np|--no-optipng]'
  echo '  -nw, --no-waifu2x'
  echo '  -np, --no-optipng'
  echo ''
  echo ''
}

_process() {
  echo "Procecing $1 ..."

  filepath=$(dirname "$1")
  original_filename=$(basename $1)
  filename="fhd_$original_filename"

  convert "$filepath/$original_filename" -resize 1920x1080\! "$filepath/$filename"

  if [ "$NO_WAIFU2X" -eq 0 ] ; then
    waifu2x -m noise -i "$filepath/$filename" -o "$filepath/w2x_$filename"
    mv "$filepath/w2x_$filename" "$filepath/$filename"
  fi

  if [ "$NO_OPTIPNG" -eq 0 ] ; then
    optipng "$filepath/$filename"
  fi

  mv "$filepath/$filename" "$filepath/$original_filename"
}

while [ $# -gt 0 ] ; do
  case "$1" in
  -nw|--no-waifu2x)
    NO_WAIFU2X=1
    shift
    ;;
  -np|--no-optipng)
    NO_OPTIPNG=1
    shift
    ;;
  -h|--help)
    _usage
    exit 2
    ;;
  *)
    _process $1
    shift
    ;;
  esac
done
