#!/bin/sh

if [ $# -ne 1 ] ; then
  echo "usage: $0 [FILENAME]"
  exit 1
fi

echo "Procecing $1 ..."

filepath=$(dirname "$1")
original_filename=$(basename $1)
filename="fhd_$original_filename"

convert "$filepath/$original_filename" -resize 1920x1080\! "$filepath/$filename"

if hash optipng; then
  optipng "$filepath/$filename"
  rm "$filepath/$original_filename"
fi

mv "$filepath/$filename" "$filepath/$original_filename"
