#!/bin/bash
# tmux status bar configuration

function ssh_sign() {
    echo -n \#\[fg=green,bg=black,bold\]ssh\#\[fg=white\]\:
    echo -n \#\[fg=cyan\]`whoami`\#\[fg=white\]\@\#\[fg=yellow\]`hostname`\#\[fg=white\]\ 
}
function load_average() {
    echo -n \#\[fg=white,bg=magenta,bold\]\ 
    echo -n \(`uptime | grep -oE \[0-9\]\[.\]\[0-9\]\[0-9\]`\)\ 
}
function ip_address() {
    echo -n \#[fg=white,bg=blue,bold]\ 
    if [ `which ip` ] ; then
        echo -n `ip addr | grep inet | grep -v 127.0.0.1 | grep -v \:\:1 | grep brd | grep -oE \(\[0-9\]\{1,3\}\[.\]\[0-9\]\{1,3\}\[.\]\[0-9\]\{1,3\}\[.\]\[0-9\]\{1,3\}\)/ | grep -oE \(\[0-9\]\{1,3\}\[.\]\[0-9\]\{1,3\}\[.\]\[0-9\]\{1,3\}\[.\]\[0-9\]\{1,3\}\)`\ 
    elif [ `which ifconfig` ] ; then
        echo -n ''
    fi
}
function external_ip() {
    if [ -x `which extip` >/dev/null 2>&1 ] ; then
        echo -n \#\[fg=white,bg=blue\]\ 
        extip | grep -oE \(\[0-9\]\{1,3\}\[.\]\[0-9\]\{1,3\}\[.\]\[0-9\]\{1,3\}\[.\]\[0-9\]\{1,3\}\)/ 
        echo -n ' '
    fi
}
function cpu_temp() {
    echo -n \#\[fg=white,bg=red,bold\]\ 
    echo -n `sensors | grep 'Core 0' | grep -oE \[0-9\.\]*\.C | head -n 1`\ 
}
function acpi_battery() {
    if [ "`acpi -b | grep -oE Discharging`" = "Discharging" ] ; then
        echo -n \#\[fg=black,bg=yellow,bold\]
        echo -n \ `acpi -b | grep 'Battery' | grep -oE \[0-9\]\[0-9\]:\[0-9\]\*`
        echo -n '/'
    else
        echo -n \#\[bg=green,fg=white,bold\]\ 
    fi
    echo -n `acpi -b | grep -oE \[0-9\]+%`\ 
}


if [ "$1" = left ] ; then
    # left status bar expansion for SSH
    if [ "${SSH_CONNECTION:+mayuge}" = "mayuge" ] ; then
        ssh_sign
    fi
elif [ "$1" = right ] ; then 
    # right status bar
    # display both (non-SSH and SSH session)
    load_average
    if [ "${SSH_CONNECTION:+mayuge}" = "mayuge" ] ; then
        # status bar configuration for SSH session
        ip_address
    else
        # for non-SSH client
        cpu_temp
        acpi_battery
    fi
fi

# reset format
echo -n \#\[default\]

